In [3]:
import pandas
import numpy as np
data = pandas.read_csv('Science.csv', index_col='ID')
i = 2
mData = data.as_matrix()
print(mData)
pit = mData[:,i]
z = np.divide(mData, pit[:,None])
k = 0
print(z)
print('---------------')

gammaK = np.sum(z[:,k][:-1]*z[:,k][1:])/np.sum(z[:,k][:-1]**2)
for k in range(1, m):
    
print(1-gammaK)

IndentationError: expected an indented block (<ipython-input-3-f4a9339d3258>, line 16)

In [10]:
import pandas
import math as m
import numpy as np
import scipy 
import scipy.stats as stats
import random
import matplotlib.pyplot as plt
import statsmodels.stats.stattools as stattool

np.set_printoptions(suppress=True)
data = pandas.read_csv('fish.csv', index_col='ID')
# This works now for first standart
ii = 0
def normalizeRows(M):
    row_sums = M.sum(axis=1)
    return M / row_sums[:, np.newaxis]

def GeneratingLogLinear(P, Avec, Asc):
    print('Avec')
    print(Avec)
    print(P)
    return Asc * np.prod(np.power(P, Avec))

def LogLinearPk(pCurr, A, Aa, n):
    summ = np.sum(GeneratingLogLinear(pCurr, Aa[s], A[s]) for s in range(n))
    pNext = [0 for i in range(n)]
    for i in range(n):
        pNext[i] = GeneratingLogLinear(pCurr, Aa[i], A[i])/summ
    return pNext
    
def dw(self):
    """
    Calculates the Durbin-Waston statistic
    """
    de = np.diff(self.e,1)
    dw = np.dot(de,de) / np.dot(self.e,self.e)

    return dw
    
def LogLinearChains(i):
    dataNorm = normalizeRows(data.as_matrix())
    mData = np.transpose(dataNorm).copy()
    tmpRow = mData[0].copy()
    mData[0] = mData[i]
    mData[i] = tmpRow
    print('---------')
    print('Select standart:', i+1)
    print('Transpose matrix.')
    print('---------')
    tmData = np.transpose(mData)
    print (tmData)
    T = mData.shape[1]
    print ('T = ', T)
    n = len(mData)
    # Computing matrix of Y
    print('-------')
    #mData = p
    Y = np.array([[(m.log(mData[k][t])- m.log(mData[0][t]))for k in range(1,n)] for t in reversed(range(1,T))])
    print ('Y = ', Y)
    Xtmp = np.array([[(m.log(mData[i][j]))for i in range(n)] for j in reversed(range(T-1))])
    # array of 1
    print ('X before concat with array of 1 = ', Xtmp)
    b = np.array([[1 for j in range(T-1)] for i in range(1)])
    X = np.concatenate((b.T, Xtmp), axis=1)
    print('X', X)
    Xt = np.transpose(X)
#   Xttmp = Xt[0].copy()
#   Xt[0] = Xt[1]
#   Xt[1] = Xttmp
    Aa = np.dot(np.dot(np.linalg.inv(np.dot(Xt, X)), Xt), Y)
    print('A~ = ', Aa)
    #---------------------------------------------------------------
    # System
    p0 = mData[:,0]
    pnext = [0 for i in range(len(p0)+1)] 
    A = np.array([(m.exp(Aa[0][i]))for i in range(n-1)])
    #--------sum from formula-------
    pnext[0] = 1 / (1 + np.sum([GeneratingLogLinear(p0, Aa[:,j][1:], A[j]) for j in range(n-1)]))
    print('PNEXT')
    print(pnext[0])
    for k in range(1,n):
        pnext[k] = GeneratingLogLinear(p0, Aa[:,k-1][1:], A[k-1]) * pnext[0]
        print('PNEXT')
        print(pnext[k])
    print('A = ',A)
    #-----epsil-------------
    epsil = Y - np.dot(X, Aa)
    print('--epsil--', epsil)
    #-------Shapir-Uilk-----
    epsRow = epsil[:,0] 
    W = stats.shapiro(epsRow)
    print('---W-crit---Shapiro')
    print(W)
    Ttest = stats.ttest_1samp(epsRow, 0)
#    print('---t test crit ---')
#    print(Ttest)
    #---if 2 - no autocorrelation, 0 - positive, 4 - negative
    DW = stattool.durbin_watson(epsRow)
    print('------Durban-Watson-------')
    print(DW)
    print('------Spearman-------------')
    SpC = stats.spearmanr(epsRow)
    print(SpC)
    #---------coef of meaning---------
    M = np.linalg.inv(np.dot(Xt, X))
    t = np.array([[Aa[i][j]/(np.std(epsil[i], ddof=1)*M[i][i])for i in range(Aa.shape[0])] for j in range(Aa.shape[1])])
    print('------coeff of meaning-----')
    print(t)
    # Need to understand which student table we need
    powerOfFree = T-1-n-1
#    print('---power of free---')
#    print(powerOfFree)
#    print('Aa')
#for i in range(6):
#    LogChains(i)
LogLinearChains(0)

---------
Select standart: 1
Transpose matrix.
---------
[[ 0.01244339  0.10302283  0.0069364   0.00762853  0.86996885]
 [ 0.01385189  0.08857219  0.00873143  0.00982656  0.87901794]
 [ 0.01312236  0.10100863  0.00970675  0.01370623  0.86245603]
 [ 0.01012477  0.09057794  0.00881973  0.01401119  0.87646637]
 [ 0.01089889  0.10697343  0.00922452  0.01339493  0.85950823]
 [ 0.00859198  0.09838972  0.0065449   0.01200859  0.8744648 ]
 [ 0.00972721  0.09375084  0.00465449  0.01040177  0.88146569]
 [ 0.00924413  0.09930571  0.00783201  0.00895647  0.87466168]
 [ 0.00723703  0.11777879  0.01093145  0.00514942  0.85890331]
 [ 0.00402062  0.08626835  0.01023721  0.00290673  0.89656709]
 [ 0.00510367  0.11043018  0.01086394  0.00238768  0.87121453]
 [ 0.0048192   0.09807232  0.01534778  0.00304909  0.8787116 ]
 [ 0.00455136  0.09363515  0.00199374  0.00278922  0.89703054]
 [ 0.00596278  0.10959436  0.00288974  0.00284661  0.87870652]
 [ 0.00674875  0.12109379  0.00549606  0.00287781  0.86378359